if (!exists("RHOME")) RHOME <- "~/dvlp/R"
source(paste(RHOME,"verbose.R",sep="/"))
source(paste(RHOME,"misc.R",sep="/"))
source(paste(RHOME,"levels.R",sep="/"))
source(paste(RHOME,"write.matrix.R",sep="/"))
source(paste(RHOME,"read.res.new.R",sep="/"))
source(paste(RHOME,"heatmap.R",sep="/"))
source(paste(RHOME,"gene.cluster.R",sep="/"))
source(paste(RHOME,"source.diffanal.R",sep="/"))
source(paste(RHOME,"randgate.R",sep="/"))

dat1 <- read.data.gp("xchip/sim062706/simula1.srt.gct")
cls1 <- read.cls("xchip/sim062706/simula1.cls")
genes1 <- read.table("xchip/sim062706/simula1.genelist.txt",sep="\t",header=F,row.names=1)

set.seed(123456)
rf1 <- randomForest( t(dat1@signal), y=as.factor(cls1), ntree=1000, importance=T )
imp1 <- varImpPlot(rf1,pch=20)
ord1 <- rev(order(imp1[,1]))
g1 <- rownames(imp1[ord1,])
rnk1 <- match(g1,rownames(genes1))
matplot(rf1$err.rate,type="l",log="x",col=c("black","red","green"))

dat2 <- read.data.gp("xchip/sim062706/simula2.srt.gct")
cls2 <- read.cls("xchip/sim062706/simula2.cls")
genes2 <- read.table("xchip/sim062706/simula2.genelist.txt",sep="\t",header=F,row.names=1)

set.seed(123456)
rf2 <- randomForest( t(dat2@signal), y=as.factor(cls2), ntree=1000, importance=T )
imp2 <- varImpPlot(rf2,pch=20)
ord2 <- rev(order(imp2[, 1]))
g2 <- rownames(imp2[ord2,])
rnk2 <- match(g2,rownames(genes2))
matplot(rf1$err.rate,type="l",log="x",col=c("black","red","green"))
